# Generated by Django 3.2.6 on 2022-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='path_to_cover_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
